### PR TITLE
Fix Fireworks

### LINKED ISSUE #90: Fireworks provider broken in v0.1.9 and v0.1.10
When I run `ghcr.io/spacedriveapp/spacebot:v0.1.8-full`, I can use my FIREWORKS_API_KEY to use Kimi K2.5 via Fireworks. However, when running `ghcr.io/spacedriveapp/spacebot:full`, I get many variations of the following error in my logs:

`spacebot  | 2026-02-20T21:23:12.378331Z ERROR handle_message{channel_id=discord:dm:214167454291722241 agent_id=main message_id=1474516757900169350}: spacebot::agent::channel: channel LLM call failed channel_id=discord:dm:214167454291722241 error=CompletionError: ProviderError: unknown provider: fireworks`

I believe this issue was specifically first introduced in v0.1.9, because it was also broken yesterday evening before v0.1.10 released.

### PR DESCRIPTION
**Pull request by Nebhay**
Fixes #90

UNTESTED AS I DONT HAVE A API KEY 

but this fix is just like the NVIDIA fix that worked fine

- **Added Fireworks base URL constant** (`src/config.rs`):
  - Added `FIREWORKS_PROVIDER_BASE_URL` constant set to `https://api.fireworks.ai/inference`
- **Added Fireworks provider registration** (`src/config.rs`):
  - Registered Fireworks provider in `load_from_env()` function (environment variable loading)
  - Registered Fireworks provider in `from_toml()` function (TOML config file loading)
  - Both use `ApiType::OpenAiCompletions` API type and the Fireworks base URL

### CODE REVIEW

**Comment by the-snesler** [comment]
I tested it with my API key and it doesn't appear to work. I'll try to figure out a working fix on my own (removing the trailing /v1 from the URL doesn't fix it either)
WindowsTerminal_6Jcy5hill0

File: src/config.rs [hunk 1]
```diff
@@ -187,6 +187,7 @@ const MOONSHOT_PROVIDER_BASE_URL: &str = "https://api.moonshot.ai";
 const ZHIPU_PROVIDER_BASE_URL: &str = "https://api.z.ai/api/paas/v4";
 const ZAI_CODING_PLAN_BASE_URL: &str = "https://api.z.ai/api/coding/paas/v4";
 const NVIDIA_PROVIDER_BASE_URL: &str = "https://integrate.api.nvidia.com";
+const FIREWORKS_PROVIDER_BASE_URL: &str = "https://api.fireworks.ai/v1";
```
Comment (the-snesler) [inline src/config.rs]: Changing to this base URL works for me!

```suggestion
const FIREWORKS_PROVIDER_BASE_URL: &str = "https://api.fireworks.ai/inference";
```

**Comment by Nebhay** [comment]
Perfect thank you,  i didn't click on the try request in the docs so i didn't see the full url with the /inference part , my bad

**Comment by Nebhay** [comment]
Fixed confict caused by gemini being added
